#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3

version=2.10.0-02

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi



# Check domain/path availability
sudo yunohost app checkurl $domain$path -a nexus
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


sudo yunohost app setting nexus admin_user -v $user

YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)

# Remove trailing "/" for next commands
path=${path%/}

# Install dependencies
sudo apt-get install -y openjdk-7-jre openjdk-7-jdk tomcat7

# Copy files to the right place

wget -P /tmp "http://download.sonatype.com/nexus/oss/nexus-latest-bundle.zip"
sudo adduser --home /opt/nexus --disabled-login --disabled-password nexus

unzip -d /opt/nexus /tmp/nexus-latest-bundle.zip
sudo ln -s /opt/nexus/nexus-$version/bin/nexus /etc/init.d/nexus


sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf


sed -i "s@NEXUS_HOME=\"\"@NEXUS_HOME=\"/opt/nexus/nexus-$version\"@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/nexus.conf



sudo addgroup nexus $user
sudo update-rc.d nexus defaults


data_path=/home/yunohost.app/nexus
sudo mkdir -p $data_path
sudo chown -hR nexus:nexus $data_path
sudo chmod 775 $data_path

# Monitor service
sudo service nexus start
sudo yunohost service add nexus




# Reload Nginx and regenerate SSOwat conf

sudo service nginx reload

sudo yunohost app ssowatconf
