#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3
port=$4

version=2.11.0-02

# Check user parameter
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong user"
    exit 1
fi



# Check domain/path availability
sudo yunohost app checkurl $domain$path -a nexus
if [[ ! $? -eq 0 ]]; then
    exit 1
fi


sudo yunohost app setting nexus admin_user -v $user

YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)

# Remove trailing "/" for next commands
path=${path%/}

# Install dependencies
sudo apt-get install -y openjdk-7-jre openjdk-7-jdk tomcat7

# Copy files to the right place

wget -P /tmp "http://download.sonatype.com/nexus/oss/nexus-$version-bundle.zip"
sudo mkdir /opt/nexus
sudo unzip -d /opt/nexus /tmp/nexus-$version-bundle.zip
sudo cp ../conf/nexus /opt/nexus/nexus-$version/bin/nexus

#add="\nRUN_AS_USER=nexus\nNEXUS_HOME=\"/opt/nexus/nexus-$version/\"\n"

#sudo sed -i "s@#RUN_AS_USER=@RUN_AS_USER=root@g" /opt/nexus/nexus-$version/bin/nexus

sudo ln -s /opt/nexus/nexus-$version/bin/nexus /etc/init.d/nexus
sudo mkdir /opt/nexus/sonatype-work
sudo chmod 775 -R /opt/nexus/
sudo chmod +x /opt/nexus/nexus-$version/bin/nexus


sudo update-rc.d nexus defaults
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@PORTTOCHANGE@$port@g" ../conf/nginx.conf

sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/nexus.conf
sudo service nexus start
sudo service nexus stop
sudo sed -i "s@application-port=8081@application-port=$port@g" /opt/nexus/sonatype-work/nexus/conf/nexus.properties
sudo service nexus start
sleep 60
wget http://localhost:$port/nexus
sleep 120
wget http://localhost:$port/nexus
sudo service nexus stop

sudo cp ../conf/security-configuration.xml /opt/nexus/sonatype-work/nexus/conf/
sudo cp ../conf/security.xml /opt/nexus/sonatype-work/nexus/conf/
sudo cp ../conf/capabilities.xml /opt/nexus/sonatype-work/nexus/conf/
sudo cp ../conf/nexus.xml /opt/nexus/sonatype-work/nexus/conf/

sudo sed -i "s@YNH_USER@$user@g" /opt/nexus/sonatype-work/nexus/conf/nexus.xml
sudo sed -i "s@YNH_USER@$user@g" /opt/nexus/sonatype-work/nexus/conf/security.xml
sudo sed -i "s@YNH_DOMAIN@$domain@g" /opt/nexus/sonatype-work/nexus/conf/nexus.xml
sudo sed -i "s@YNH_EMAIL@$user\@$domainc@g" /opt/nexus/sonatype-work/nexus/conf/nexus.xml
sudo sed -i "s@YNH_EMAIL@$user\@$domain@g" /opt/nexus/sonatype-work/nexus/conf/security.xml


sudo service nexus start

data_path=/home/yunohost.app/nexus
sudo mkdir -p $data_path
sudo chown root:nexus -R $data_path
sudo chmod 775 $data_path

# Monitor service

sudo yunohost service add nexus

# Reload Nginx and regenerate SSOwat conf

sudo service nginx reload

sudo yunohost app ssowatconf
