#!/bin/bash


sudo yunohost service remove nexus
domain=$(sudo yunohost app setting nexus domain)

sudo rm /etc/nginx/conf.d/$domain.d/nexus.conf

sudo service nexus stop

sudo deluser nexus
sudo rm -r /opt/nexus/
sudo rm /etc/init.d/nexus

sudo service nginx reload
sudo yunohost app ssowatconf 
